// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xbaalrlwhgvovxrnbbep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhiYWFscmx3aGd2b3Z4cm5iYmVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MjIwMjYsImV4cCI6MjA2Nzk5ODAyNn0.mrGqAaOwFaBy1FJNhChAaAASsh4k5axpQkxA2Hspq0Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});